name: 'Create AWS Profile'
description: 'Creates an AWS profile from environment variables'
inputs:
  access-key-id-var:
    description: 'Environment variable containing the access key id'
    required: true
    default: 'AWS_ACCESS_KEY_ID'
  secret-access-key-var:
    description: 'Environment variable containing the secret access key'
    required: true
    default: 'AWS_SECRET_ACCESS_KEY'
  session-token-var:
    description: 'Environment variable containing the session token'
    required: true
    default: 'AWS_SESSION_TOKEN'
  profile-name:
    description: 'Name of the profile to create'
    required: true
runs:
  using: "composite"
  steps: 
    - run: |
        FILE_NAME=${AWS_SHARED_CREDENTIALS_FILE:-$RUNNER_TEMP/.aws/credentials}
        echo "AWS_SDK_LOAD_CONFIG=true" >> $GITHUB_ENV # Needed for the JS AWS SDK to use AWS_SHARED_CREDENTIALS_FILE
        echo "AWS_SHARED_CREDENTIALS_FILE=$FILE_NAME" >> $GITHUB_ENV
        mkdir -p "$(dirname "$FILE_NAME")"
        echo "[${{ inputs.profile-name }}]" >> $FILE_NAME
        echo "aws_access_key_id = $${{ inputs.access-key-id-var }}" >> $FILE_NAME
        echo "aws_secret_access_key = $${{ inputs.secret-access-key-var }}" >> $FILE_NAME
        echo "aws_session_token = $${{ inputs.session-token-var }}" >> $FILE_NAME
      shell: bash
